export const SAVE_TOKEN = "SAVE_USER_TOKEN";
export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const SAVE_SHOP_CATEGORY_LIST = "SAVE_SHOP_CATEGORY_LIST";
export const SET_ASSOCIATE_STORE = "SET_ASSOCIATE_STORE";
// export const SET
